# Generated by Django 2.1.2 on 2019-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2019-01-29 12:13:00', help_text='创建时间', null=True),
        ),
    ]
