# Generated by Django 2.1.2 on 2019-02-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='admin_user_id',
            new_name='article_id',
        ),
    ]
