# Generated by Django 2.1.5 on 2019-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0002_articlecomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecomment',
            table='article_comment',
        ),
    ]
