# Generated by Django 2.1.5 on 2019-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0003_auto_20190322_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='status',
            field=models.IntegerField(default=0, help_text='状态0表示草稿 1表示已经审核通过'),
        ),
    ]
