# Generated by Django 2.1.2 on 2019-05-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0005_cate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0, help_text='评论数量', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='like_num',
            field=models.IntegerField(default=0, help_text='点赞数量', null=True),
        ),
    ]
