# Generated by Django 2.1.2 on 2019-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0006_auto_20190516_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0, help_text='文章id')),
                ('ip', models.CharField(default='', help_text='评分的IP地址', max_length=200)),
                ('rate_value', models.FloatField(default=0, help_text='本次分值')),
                ('created_at', models.DateTimeField(blank=True, default='2019-01-29 12:13:00', help_text='创建时间', null=True)),
            ],
            options={
                'db_table': 'article_rate',
            },
        ),
    ]
