# Generated by Django 2.1.2 on 2019-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0008_auto_20190518_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0, help_text='类型ID')),
                ('type_key', models.CharField(default='', help_text='类型的key', max_length=200)),
                ('path', models.CharField(default='', help_text='存储路径', max_length=200)),
                ('desc', models.CharField(blank=True, default='', help_text='类型描述', max_length=200, null=True)),
                ('allow_type', models.CharField(help_text='允许的文件后缀名', max_length=200, null=True)),
                ('allow_size', models.IntegerField(help_text='允许文件的大小', null=True)),
                ('allow_num', models.IntegerField(help_text='允许文件的数量', null=True)),
            ],
            options={
                'db_table': 'uploadfile_type',
            },
        ),
    ]
